# fly.toml app configuration file generated for libraryproject-client on 2025-09-30T06:08:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'libraryproject-client'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
